st-zfs-send-recv: die if missing config

diff --git a/scripts/st-zfs-send-recv b/scripts/st-zfs-send-recv
--- a/scripts/st-zfs-send-recv
+++ b/scripts/st-zfs-send-recv
@@ -21,7 +21,12 @@
 ####  initialization and checks
 ###############################################################################
 
-[[ -e /etc/${0##*/}.conf ]] && source /etc/${0##*/}.conf
+if [[ -e /etc/${0##*/}.conf ]] ; then
+    source /etc/${0##*/}.conf
+else
+    echo "missing config file: '/etc/${0##*/}.conf'"
+    exit 1
+fi
 
 # we want boring english messagges
 LC_ALL=C
@@ -37,6 +42,7 @@ declare -A cmd
 # check that we are root
 if test ${UID} -ne 0 ; then
     echo "ERROR: need root privileges"
+    exit 1
 fi
 
 # initialize the cmd array it will be possible to call the command
